name: Create flows

on:
  workflow_dispatch:
    inputs:
      upload:
        description: Upload flows to RapidPro
        type: boolean
        required: false
        default: false

jobs:
  pipeline:
    uses: IDEMSInternational/parenttext-core/.github/workflows/create.yaml@main
    secrets:
      google_credentials: ${{ secrets.CREDENTIALS }}
